#:schema https://fnox.jdx.dev/schema.json

[providers]
age = { type = "age", recipients = ["age1m78uhvvgrwg63cp9dcwr64hvjmzyj8cemmr9vlsvgnj6ydnvaguq8cg7tn"] }

[secrets]
INFISICAL_MIRROR_URL= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZVQ2cElmQmo1a3drQ1IrNHRFZ1BLWStlNG1sVHVJdzBWeFl0SStJK2hBCm1KSjA0Qk9PMEtlK0Z3QzVoczJ6ZDVnUU1zZCtpZkh5aVMwU1EyZit3M2sKLT4gYDo0OVotZ3JlYXNlIDJmSSBZdS5rCkNGLytyd0tCcEVzNXR4NlJndwotLS0gTVZSNjBXS1ZNd0x2ZTR0aWNGTU56ekt5Y2MwQnhaN3FOTXNaUXJBTXBsNAqx0t475h6DDKBBFvCQDHDv7ylka8veP+I1/IuqS+tuCaEwiOke+bD8xiOCoGNiUGElz9wRIe7J992m8cs9vp+84D4VbmooMio=" }
INFISICAL_MIRROR_USERNAME= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHNTdBemJTVis3K1hVajgwUzhEb2hzY2N4MGl4d3V3MzZWaTNRNlM5MkN3CkJEK2VBZnEycE5FVlA1Q0pmL0tWQmVnSE1WaHlyOCtia2hpZ082YVdrR0UKLT4gbV9bTy1ncmVhc2UgYSBNCjAyZGNpaTZwWFB3NFZOU0d5NDFxOTRINjAzWU1IKzFGKzllZk1aZXBuQWZ2TndhSDUxcVNzNHo5WnlMbDVEbisKU0wyek5rYmVtQ2FyaVJGcwotLS0gR0o0NnZGSjd2NkxtdDFhQURYQ3lTdHVtWnU0bVJaNnUzNWZ4bUJCVnJQTQrSpb4jW3raLm9HiN5rugTwY3ZMEOVLusBvcS/TE/bPsLopjEV4o/g=" }
INFISICAL_MIRROR_TOKEN= { provider = "age", value = "YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwWmxBblprL1llYjF3UlZrVGZZTDM1dUlKQlhrdmFTVDMxVGI3SVZab2t3CjZNenIvMmsxa3pDVjFCZUc4T2FtVFdtUU4ya0dySGVwckZadHBlcHNsaTAKLT4gX0omLzJ6WS1ncmVhc2UKaFpORUhSVFJTNzRpZFdEdQotLS0gMTFmbDB5eWQrQ0U0di9TSkFCcUJud0l0Wm15dkl1Y0V5M2NXWEtTVGN1NAp99b8WAMbYgBLidgwepchy0hnZ3EGsjeCDB8FdGme3xpYA/F5XMHJf8htByStGiUK2zy4CISioA9HMdqnvlHyvd/wOhaq9Dk17/yH0IFeojxMCj6Eu5mdkBoXW3Z58h5X5koe/psFU/q0bGAzAQxMpQ0Jel9f5t8874M/RuQ==" }
# INFISICAL_MIRROR_URL      目标私有仓库的 HTTPS 地址
# INFISICAL_MIRROR_USERNAME 目标远端的 HTTPS 用户名
# INFISICAL_MIRROR_TOKEN    目标远端的 HTTPS token（GitHub PAT）
#
# 用 `fnox set` 写入真实值（默认使用上面的 age provider 加密）：
#   fnox set INFISICAL_MIRROR_URL https://github.com/you/infisical.git
#   fnox set INFISICAL_MIRROR_USERNAME you
#   fnox set INFISICAL_MIRROR_TOKEN ghp_xxx
