[[mirrors]]
repository = "https://github.com/YewFence/actions.git"

[[mirrors]]
repository = "https://github.com/MDX-Tom/gpt-5.6-instruct.git"

[[mirrors]]
repository = "https://github.com/jhl337/Auto_WeLearn.git"

[[mirrors]]
repository = "https://github.com/34306/vphone-aio.git"
